### ISSUE TITLE
Help with Implementation

### ISSUE THREAD

**Issue by robmontesinos** [mbleigh/escapable-amp#2]
Hello Michael. I have watched this video no less than ten times. Cudos to you for presenting such a compelling and exciting strategy for performance. I am having difficulty implementing this approach into my current project(s) particularly implementing the bucket proxy and storage.

I am getting the following error (I added 'err' to Not Found in app.ts in rs.on("error"):
`Not Found: ApiError: No such object: xxxxx.appspot.com/some-folder/some-file.html`

Questions:
1. Do I have to load storage with static files of each possible request, i.e. one per document in Firestore?
2. Or should I build in a test to see if the file exists in storage, and if not, render the page and deliver a copy to storage afterwards, and if so, how is this accomplished?
3. Is there more information besides the video, e.g. blog article or tutorial?

Thank you so much @mbleigh !!

**Comment by mbleigh** [comment]
Yes, I'd handle the not found error and fall back to render + store in that case. Better than this, though, is to pro-actively render content when the data changes rather than relying on a fallthrough. If you do this, you can just render a generic 404 page if the object isn't found in storage.

Unfortunately the talk and this repo are the only resources for this particular info, but I hope that helps a little!

**Comment by robmontesinos** [comment]
Thank you Michael for the quick response - that was a huge help. Salud!!
